###
DELETE http://localhost:3001/api/persons/6415d4cc0b427d38a49ced33

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{ 
    "name": "bru", 
    "number": "39-22"
}

###
GET http://localhost:3001/api/persons 

###

GET http://localhost:3001/api/persons/6415d4cc0b427d38a49ced33